# Generated by Django 3.1 on 2020-09-09 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.DecimalField(decimal_places=0, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=15)),
                ('edad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.edad')),
                ('especie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.especie')),
                ('localidad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.localidad')),
                ('raza', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.raza')),
                ('sexo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appMascotas.sexo')),
            ],
        ),
    ]
