# Generated by Django 3.1 on 2020-09-09 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='nombre',
        ),
    ]
