# Generated by Django 3.2.dev20200824123207 on 2020-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0002_remove_publicacion_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
