# Generated by Django 3.0 on 2020-09-22 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0004_publicacion_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fechavence',
            field=models.DateField(default=datetime.date(2020, 9, 28)),
        ),
    ]
