# Generated by Django 3.1 on 2020-09-23 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0005_publicacion_fechavence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechavence',
            field=models.DateField(default=datetime.date(2020, 9, 30)),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
