# Generated by Django 3.1.1 on 2020-09-27 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0006_auto_20200923_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fechavence',
            field=models.DateField(default=datetime.date(2020, 10, 4)),
        ),
    ]
