# Generated by Django 3.1.1 on 2020-09-28 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMascotas', '0007_auto_20200927_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edad',
            name='edad',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fechavence',
            field=models.DateField(default=datetime.date(2020, 10, 5)),
        ),
    ]
